### ISSUE TITLE
Can't export PNG from Quad_Player_Mobile and image are in wrong positions when export ZIP

### ISSUE THREAD

**Issue by HLI5KY** [rufaswan/Web2D_Games#3] opened 2023-09-16 07:20 UTC
1.I start the player by double-click the `player-mobile.tpl.html`
2.When I click "PNG" button, It fails with:
```
Uncaught RangeError: Invalid array length
    at Array.push (<anonymous>)
    at QuadFunc.$.arrayRepeat (player-mobile.tpl.html:750:9)
    at QuadGL.$.createPixel (player-mobile.tpl.html:593:27)
    at button_export_png (player-mobile.tpl.html:2021:25)
    at button_export (player-mobile.tpl.html:2123:16)
    at HTMLButtonElement.onclick (player-mobile.tpl.html:1:1)
```

3.I can export ZIP but there is something wrong with the content. Part of the content is out of the image. 
![0000](https://github.com/rufaswan/Web2D_Games/assets/131789096/20c48123-15eb-4c63-a1fa-d9cb7dc4311a)

**Comment by rufaswan** [comment] 2023-09-17 12:17
1+2) I would guess it is the same problem why it doesn't work on my phone, and on Sophignon's desktop:
https://www.vg-resource.com/thread-38430-post-677757.html#pid677757

The PNG sheet uses GPU max texture size for PNG size, so it will use a lot of GPU memory. I would guess your GPU might run of VRAM. Can I post your computer spec and your GPU spec for reference?


3 )  It is known. It is still WIP, so I hardcoded the size as 256x256, and in middle of working on auto-size-detection code to fix it. It would be a pain to manually input the size multiple times until you got it right anyway.

Thanks!
- Rufas

**Comment by HLI5KY** [comment] 2023-09-18 08:43
1+2）I'm glad to post my computer spec and GPU spec here:
```
Legion R7000P2020H
CPU:  AMD Ryzen 7 4800H with Radeon Graphics            2.90 GHz
RAM: 16GB
GPU: GeForce RTX 2060 with 6GB VRAM 
```

3 ) I've found the way to get full image by modifying values of  `camera`  in function `button_export_zip` and parament `size` at line 2120. XD

Thanks for your hard work.

**Comment by rufaswan** [comment] 2023-09-18 13:41
Nice! It is an open source project, so feel free to play around the parameters :)

If you want to, try modify the line 2017 on the HTML file:

    var maxsz = QUAD.gl.maxTextureSize() >> 1;

This is the max texture size I talked about. I realized it will be causing errors, so I half its value. Guess that didn't work. Can you try change it to something lower, like 1024, to see if PNG works for you now?

    var maxsz = 1024;

Thanks!

**Comment by HLI5KY** [comment] 2023-09-18 14:56
Wow! It works. And I find that the max size my computer can support is about `1024 << 2`

Thanks a lot!

**Comment by rufaswan** [comment] 2023-09-18 16:44
Interesting! So your max size is about 4096 (or 4K HD), that means maxTextureSize() must be returning 16K and above. WOW!

Not sure how to auto-detect this. Will need to look around.

Thanks for your feedback!

**Comment by rufaswan** [comment] 2023-10-02 14:23
Updated Quad Player to ver-2023-10-2. Now both PNG and ZIP option works on my phone, let me know if it works for you too. Thanks!

**Comment by HLI5KY** [comment] 2023-10-04 07:27
Yes. It works on my device. I can download both png and zip now. But there is still something wrong with the position of camera, it makes some png be empty.

![REHD_Alice_mbs_v55_quad_skeleton_35_0](https://github.com/rufaswan/Web2D_Games/assets/131789096/46f22ee7-d6a8-48b7-896b-142654dae2f2)

**Comment by rufaswan** [comment] 2023-10-04 15:16
I tried it on my end, and it works fine. You are using REHD_Alice_mbs_v55_quad_skeleton_35_0 , right?

Here is my PNG output:

![REHD_Alice_mbs_v55_quad_skeleton_35_0](https://github.com/rufaswan/Web2D_Games/assets/2883355/b728b615-4679-4f12-a117-cd604cb5a560)

Since I couldn't reproduce it, I couldn't fix it either. I'll consider this issue is done and close it. Is it OK with you?

**Comment by HLI5KY** [comment] 2023-10-05 11:40
OK. Thank you very much. :)

**Closed as completed** 2023-10-05 11:40 UTC
Labels: bug
